// ACTIONS //
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_ERROR = 'FETCHING_DATA_ERROR';
export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_APOD_DATA = 'FETCHING_APOD_DATA';
export const FETCHING_APOD_DATA_SUCCESS = 'FETCHING_APOD_DATA_SUCCESS';
export const FETCHING_APOD_DATA_ERROR = 'FETCHING_APOD_DATA_ERROR';
export const FETCHING_ROVER_DATA_SUCCESS = 'FETCHING_ROVER_DATA_SUCCESS';
export const FETCHING_ROVER_DATA_ERROR = 'FETCHING_ROVER_DATA_ERROR';
